{% set name = "spacy-lookups-data" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spacy_lookups_data-{{ version }}.tar.gz
  sha256: 290db7600987157b9e924075a58bb3bcb725897d8f6c6c7d50a67db350b273a0

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools

test:
  imports:
    - spacy_lookups_data

about:
  home: https://github.com/explosion/spacy-lookups-data
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Additional lookup tables and data resources for spaCy'

  # The remaining entries in this section are optional, but recommended.
  description: |
    This package contains additional data files to be used with spaCy v2.2+.
    When it's installed in the same environment as spaCy, this package makes
    the resources for each language available as an entry point, which spaCy
    checks when setting up the Vocab and Lookups.
  doc_url: https://spacy.io/
  dev_url: https://github.com/explosion/spacy-lookups-data

extra:
  recipe-maintainers:
    - honnibal
    - ines
